version: '3.8'

services:
  flipt:
    image: viettditech/flipt-custom:v1.0.0
    ports:
      - "8080:8080"
    environment:
      - FLIPT_DB_URL=postgres://viettd:postgres@host.docker.internal:5432/flipt_1?sslmode=disable
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_META_TELEMETRY_ENABLED=false
      - FLIPT_CACHE_ENABLED=true
      - FLIPT_CACHE_TTL=60s
      - FLIPT_CACHE_BACKEND=redis
      - FLIPT_CACHE_REDIS_HOST=redis
      - FLIPT_CACHE_REDIS_PORT=6379
    volumes:
      - ./flipt-config.yml:/etc/flipt/config/flipt-config.yml
      - ../opa-policy:/etc/flipt/policy
    command: [ "./flipt", "--force-migrate", "--config", "/etc/flipt/config/flipt-config.yml" ]
    networks:
      - flipt_net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - flipt_net

networks:
  flipt_net:
    driver: bridge

