version: "1.0"

server:
  http_port: 8080

authentication:
  required: true
  session:
    domain: localhost:8080
  methods:
    oidc:
      enabled: true
      providers:
        keycloak:
          issuer_url: "https://keycloak.dev.itech.asia/realms/business-employee-portal"
          client_id: "new-flipt-client"
          client_secret: "IFfXXjLtIKl06pSauWN6boHLnMa8aBhh"
          redirect_address: "http://localhost:8080"
          namespace_claim: "allowed_namespaces"

authorization:
  required: true
  backend: local
  local:
    policy:
#      path: "./deployments/opa-policy/policy.rego"
      path: "/etc/flipt/policy/policy.rego"

db:
  url: "postgres://viettd:postgres@localhost:5432/flipt_1?sslmode=disable"
