version: "1.0"

server:
  protocol: https
  host: 0.0.0.0
  http_port: 8080
  https_port: 443
  cert_file: /etc/ssl/certs/flipt.pem
  cert_key: /etc/ssl/private/flipt.key

authentication:
  required: true
  session:
    domain: localhost:8080  # Change this to your domain in production
    token_lifetime: 24h
    secure: true
  methods:
    oidc:
      enabled: true
      providers:
        keycloak:
          issuer_url: "https://keycloak.dev.itech.asia/realms/business-employee-portal"
          client_id: "new-flipt-client"
          client_secret: "IFfXXjLtIKl06pSauWN6boHLnMa8aBhh"
          redirect_address: "http://localhost:8080" # Change this to your redirect address in production
          namespace_claim: "allowed_namespaces"

authorization:
  required: true
  backend: local
  local:
    policy:
      path: "/etc/flipt/policy/policy.rego"

db:
  url: "${DATABASE_URL}"
  max_idle_conn: 10
  max_open_conn: 50
  conn_max_lifetime: 300s

cache:
  enabled: true
  backend: redis
  ttl: 300s
  redis:
    host: "${REDIS_HOST}"
    port: "${REDIS_PORT}"
    password: "${REDIS_PASSWORD}"
    db: "${REDIS_DB}"
    require_tls: true
    pool_size: 50
    min_idle_conn: 2
    conn_max_idle_time: 10m
    net_timeout: 500ms
